fruits = []

f1 = input("Enter the name of a fruit: ")
fruits.append(f1)
f2 = input("Enter the name of another fruit: ")
fruits.append(f2)
f3 = input("Enter the name of a third fruit: ")
fruits.append(f3)
f4 = input("Enter the name of a fourth fruit: ")
fruits.append(f4)
f5 = input("Enter the name of a fifth fruit: ")
fruits.append(f5)
f6 = input("Enter the name of a sixth fruit: ")
fruits.append(f6)
f7 = input("Enter the name of a seventh fruit: ")
fruits.append(f7)
print(fruits)